config/routes.rb
StudentApp::Application.routes.draw do
  root :to => 'students#home'
  get "issuedbook/submitbook"
  get "issuedbook/issuebook"
  post "issuedbook/saveissuebook"
  resources :book 
  get :'students/logout'
  get :'students/login'
  post :'students/check_login'

  resources :students
  

  

   

end

app/models/books.rb
class Books < ActiveRecord::Base
  has_one :issuedbook
end

app/models/issuedbook.rb
class Issuedbook < ActiveRecord::Base
   belongs_to :book
   belongs_to :student
   validates_presence_of:book_id 
   validates_presence_of:student_id
end

app/models/student.rb
class Student < ActiveRecord::Base

  has_many:issuedbook,:dependent => :destroy


  validates_uniqueness_of :user,:email
  validates_presence_of :user, :password, :role, :first_name, :last_name, :address, :college
  validates_size_of :user, :password, :within => 5..15
  validates_format_of :address,:college, :with => /^\w+$/i,
  :message => "can only contain letters and numbers."
  validates_format_of :first_name,:last_name,:with => /^[-a-z]+$/,
  :message=> "first name and last name must be alphabet only "

  
  def self.check_password(username,password)
    #self.where("user = ? AND password = ?",username,password)
    Student.find(:first, :conditions => ["user=? And password=?",username,password])
  end
  
  def is_admin?
    self.role == "a" ? true : false
  end
  
  def is_librarian?
    self.role=="l" ? true : false
  end
  
  def is_user?
    self.role == "u" ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  layout "standard"
  before_filter :require_login
  skip_before_filter :require_login, :only => [:login, :check_login,:home]

  def require_login
    if session[:student].nil?
      flash[:error] = "You must be logged in to access this section"
      redirect_to :action=>'login' # halts request cycle
    end
  end
  
  def current_user
    return session[:student]
  end
end

app/controllers/book_controller.rb
class BookController < ApplicationController
   def new
    @book = Books.new
    respond_to do |format|
      format.html # addbook.html.erb
      format.json { render :json => @book }
    end
  end
  
  def index
    #  if session[:student].nil?
    #    flash[:notice]="session expired"
    #    redirect_to :action=>'login' and return
    @book = Books.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json =>@book}
    end
  end

  
  def create
  
    @book = Books.new(params[:books])
    respond_to do |format|
      if @book.save
        format.html { redirect_to  @book, :notice => 'Book was successfully added.' }
        format.json { render :json => @book, :status => :created, :location =>  showbook_student_path(@book) }
      else
        format.html { render :action => "addbook" }
        format.json { render :json => @book.errors, :status => :unprocessable_entity }
      end
    end
  end
  
 def destroy
    @book = Books.find(params[:id])
    @book.destroy
    respond_to do |format|
      format.html { redirect_to book_index_url }
      format.json { head :no_content }
    end
  end 
  
  def show
    @book = Books.find(params[:id])
    respond_to do |format|
      format.html # showbook.html.erb
      format.json { render :json => @book }
    end
  end
end

app/controllers/issuedbook_controller.rb
class IssuedbookController < ApplicationController
  
  def submitbook
    respond_to do |format|
      format.html  
      format.json { render :json => @availablebooks }
    end
  end 
  
 
  def issuebook
    respond_to do |format|
      format.html  
      format.json { render :json => @availablebooks }
    end
  end
   
  def saveissuebook 
    @issuebook = Issuedbook.new(params[:issuedbook])
    @issuebook.issued_date=Date.today
    @issuebook.is_issued=true
    respond_to do |format|
      if @issuebook.save        
        format.html { redirect_to issuedbook_issuebook_path,:notice => 'Book was successfully issued.' }
      else
        format.html { render :action => "issuebook" }
      end
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
 
 # layout "after_login_layout", :only => [:lougout,:index,:show,:new,:edit,:create,:update,:distroy]
  
 # layout :another_by_method

#  def another_by_method
#     if session[:student].nil?
#      "standard"      
#    else
#      "after_login_layout"
#    end
#  end

 
 
  
  def logout
    session[:student]=nil;
    flash[:notice] = "Logout Successfully"
    redirect_to :action => 'login'
  end
   
  def home
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json =>@students}

    end
  end
   
  def login
    @student = Student.new
    respond_to do |format|
      format.html # login.html.erb
      format.json { render :json => @student }
    end
  end
   
  def check_login
    username = params[:student][:user]
    password = params[:student][:password]
    student = Student.check_password(username,password)
    if student.nil?
      #redirect_to students_login_path
      flash[:notice] = "User id or user password is not correct. please enter valid id and password"
      redirect_to :action => 'login'
    else
      session[:student] = student
      if student.is_admin? 
        flash[:notice] = "Welcome  "+student[:first_name].to_s+" "+student[:last_name].to_s
        redirect_to :action => 'index'
      else
         if student.is_user?
          flash[:notice] = "Welcome  "+student[:first_name].to_s+" "+student[:last_name].to_s
          redirect_to :action => 'index'
         else
             flash[:notice] = "Welcome  "+student[:first_name].to_s+" "+student[:last_name].to_s
              redirect_to :controller=>'book', :action=>'index'
         end
      end   
    end
  end
   
  def index
    #  if session[:student].nil?
    #    flash[:notice]="session expired"
    #    redirect_to :action=>'login' and return
    @students = Student.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json =>@students}
    end
  end

  def show
    @student = Student.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])
    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, :notice => 'Student was successfully created.' }
        format.json { render :json => @student, :status => :created, :location => @student }
      else
        format.html { render :action => "new" }
        format.json { render :json => @student.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /students/1
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])
    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to @student, :notice => 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @student.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @student = Student.find(params[:id])
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user
    return session[:student]
  end
  
  def remaining_books 
    Books.find_by_sql("select books.id,books.book_name from books where id not in(select book_id from issuedbooks)")  
  end
  
  def allstudent
      Books.find_by_sql("select * from students where role like 'u' ")  
  end
  
  def issued_book_list
    Books.find_by_sql("select books.id,books.book_name from books where id in(select book_id from issuedbooks where is_issued=true)")      
  end
  
  def student_having_book
    Books.find_by_sql("select students.id,students.email from students where students.id in(select student_id from issuedbooks where is_issued=true)")   
  end
  
    
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/issuedbook_helper.rb
module IssuedbookHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/book/index.html.erb
<%= notice %>
<center><h2>Listing books</h2>
  <table border=1>
    <tr>
      <th>book_name</th>
      <th>Author</th>
      <th>Edition</th>
      <th>Publisher</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <% @book.each do |book| %>
     <tr class="<%= cycle("even", "odd") %>">
        <td><%= book.book_name %></td>
        <td><%= book.author %></td>
        <td><%= book.edition %></td>
        <td><%= book.publisher %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %> </td>
        <td><%= link_to 'Destroy',book, :method =>:delete, :confirm => 'Are you sure?' %></td>
      </tr>
    <% end %>
  </table>
</center>

app/views/book/new.html.erb
<%= form_for @book, :url => { :action => "create"},:method =>"post",:html => {:class => "nifty_form"} do |f| %>

  <div class="form_content">
    <h2 >Enter Details Here</h2>
    <div class="field1"> 
      <%= f.label :book_name %>
    </div>
    <div id="user">
      <%= f.text_field :book_name %>
    </div>
    <div class="field2"> 
      <%= f.label :author %>
    </div>
    <div id="password">
      <%= f.text_field :author %>
    </div>
    <div class="field3"> 
      <%= f.label :edition %>
    </div>
    <div id="role">
      <%= f.text_field :edition %>
    </div>
    <div class="field4">
      <%= f.label :publisher%>
    </div>
    <div id="email">
      <%= f.text_field :publisher %>    
    </div>
    <div id="actions">
      <%= f.submit %>
    </div>
  </div> 
<%end%>

app/views/book/show.html.erb
<p id="notice"><%= notice %></p>
<table border=1 align="center">
  <tr>
    <td><b>Book_name:</b></td>
     <td> <%= @book.book_name %></td>
  </tr>

  <tr>
    <td><b>Author</b></td>
    <td>  <%= @book.author %></td>
  </tr>

  <tr>
    <td><b>Edition</b></td>
    <td><%= @book.edition %></td>
  </tr>

  <tr>
    <td><b>Publisher</b></td>
    <td>    <%= @book.publisher %></td>
  </tr>

  <tr>
    <td colspan=2><b><%= link_to 'Edit', edit_student_path(@student) %></b></td>
  </tr>
</table>

app/views/issuedbook/issuebook.html.erb
<%= javascript_include_tag "application" %>
<%=form_tag({:controller => "issuedbook", :action => "saveissuebook"}, :method => "post", :class => "nifty_form") do%>
 
  <div class="form_content">
    <% unless notice.nil?%>
      <%=javascript_tag "alert('Book issued successfully')"%>
    <% end %>
      
    <h2 >Select Details Here</h2>
    <div class="field1"> 
      <%= label_tag(:q, "Email:") %>
    </div>
    <div id="email">
      <%=collection_select(:issuedbook, :student_id, allstudent, :id, :email, :prompt => 'Select email')%>
    </div>
    <div class="field2"> 
      <%= label_tag(:q, "Books:") %>      
    </div>
    <div id="password">
      <%unless remaining_books.empty? then%>
        <%=collection_select(:issuedbook, :book_id, remaining_books, :id, :book_name, :prompt => 'Select Book')%>
      <%else %>
        <%=javascript_tag "alert('No books available for issue')"%>
       <%end%>       
    </div>
    <div id="actions">
      <%= submit_tag("Issue book") %>
    </div>
  </div>
<% end%>

app/views/issuedbook/submitbook.html.erb
<%= javascript_include_tag "application" %>
<%=form_tag({:controller => "issuedbook", :action => "student_issued_books"}, :method => "post", :class => "nifty_form") do%>

 <%=javascript_tag "
 function getstudentid(){alert('item selected')}"%>

 
  <div class="form_content">
    <% unless notice.nil?%>
      <%=javascript_tag "alert('Book submited successfully')"%>
    <% end %>
      
    <h2 >Select Details Here</h2>
    <div class="field1"> 
      <%= label_tag(:q, "Email:") %>
    </div>
    <div id="email">
     <%=collection_select(:issuedbook, :student_id, student_having_book, :id, :email,{}, html_option={:onchange => 'getstudentid();'})%>
     
    
     
    </div>
    <div class="field2"> 
      <%= label_tag(:q, "Books:") %>      
    </div>
    <div id="password">
      <%unless remaining_books.empty? then%>
        <%=collection_select(:issuedbook, :book_id, issued_book_list, :id, :book_name, :prompt => 'Select Book')%>
      <%else %>
        <%=javascript_tag "alert('No books available for issue')"%>
       <%end%>       
    </div>
    <div id="actions">
      <%= submit_tag("proceed") %>
    </div>
  </div>
<% end%>

app/views/layouts/after_login_layout.html.erb
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag "application" %>
  <div class="header">
    <h1>Student Management</h1>
  </div>

  <div class="menu">
  <ul>
  <li><%= link_to 'Home', root_path %></li>
  <li><% if current_user.role == "a"%><%= link_to 'New Student', new_student_path %><%end%></li>
  <li><a href="#">Contact</a></li>
  <li><a href="#">About</a></li>
  <li><%= link_to 'Logout',students_logout_path%></li>
  </ul> 
  </div>

  <div class="mid">
    <%= yield -%>
    </div>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentApp</title>
    <%= javascript_include_tag :defaults %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "prototype" %>
    <%= javascript_include_tag "rails" %>
    <%= javascript_include_tag "login_page" %>
    <%= stylesheet_link_tag "scaffold" %>
    <%= stylesheet_link_tag "home" %>
    <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/standard.html.erb
<%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag "application" %>
  <div class="header">
    <h1>Student Management</h1>
  </div>

  <div class="menu">
  
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <%if current_user.nil?%><li><%= link_to 'Login', students_login_path %></li><%end%>
    <%unless current_user.nil? then if current_user.role=="l" then%><li><%= link_to 'AddBook', new_book_path %></li><%end end %>
    <%unless current_user.nil? then if current_user.role=="l" then%><li><%= link_to 'IssueBook', issuedbook_issuebook_path%></li><%end end%>
    <%unless current_user.nil? then if current_user.role=="a" then%><li><%=link_to 'New Student', new_student_path %></li><%end end%>
     <%unless current_user.nil? then if current_user.role=='a' then%><li><%= link_to 'Students List',students_path%></li><%end end%>
     <%unless current_user.nil? then if current_user.role=='l' then%><li><%= link_to 'Books List',book_index_path%></li><%end end%>
     <%unless current_user.nil? then if current_user.role=='l' then%><li><%= link_to 'Submit book',issuedbook_submitbook_path%></li><%end end%>
   
    <%unless current_user.nil?%><li><%= link_to 'Logout',students_logout_path%></li><%end%>
    <%unless current_user.nil?%><li class="welcome"><%=(current_user.first_name+" " +current_user.last_name).capitalize %> </li><%end%>
 </ul> 
 
  </div>

  <div class="mid">
    <%= yield -%>
  </div>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% @student.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <div class="form_content">
    <h2 >Enter Details Here</h2>
    <div class="field1"> 
      <%= f.label :user %><br />
    </div>
    <div id="user">
      <%= f.text_field :user %>
    </div>
    <div class="field2"> 
      <%= f.label :password %>
    </div>
    <div id="password">
      <%= f.password_field :password %>
    </div>
    <div class="field3"> 
      <%= f.label :role %>
    </div>
    <div id="role">
      <%= f.select :role, options_for_select([["Admin", "a"], ["User", "u"],["Librarian", "l"]]) %>
    </div>
    <div class="field4">
      <%= f.label :email %>
    </div>
    <div id="email">
      <%= f.text_field :email %>
    </div>
    <div class="field5">
      <%= f.label :first_name %>
    </div>
    <div id="first_name">
      <%= f.text_field :first_name %>
    </div>
    <div class="field6">
      <%= f.label :last_name %>
    </div>
    <div id="last_name">
      <%= f.text_field :last_name %>
    </div>
    <div class="field7">
      <%= f.label :address %>
    </div>
    <div id="address">
      <%= f.text_field :address %>
    </div>
    <div class="field8">
      <%= f.label :college %>
    </div>
    <div id="college">
      <%= f.text_field :college %>
    </div>
    <div id="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>
<%= render 'form' %>

app/views/students/home.html.erb
<%= stylesheet_link_tag 'application' %>
<div class="mid">
</div>
 
  

app/views/students/index.html.erb
<%= notice %>
<center><h2>Listing students</h2>
<table border=1>
  <tr>
    <th>User</th>
    <th>Password</th>
    <th>Role</th>
    <th>First name</th>
    <th>Last name</th>
    <th>Address</th>
    <th>College</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <% @students.each do |student| %>
    <tr class="<%= cycle("even", "odd") %>">
      <td><%= student.user %></td>
      <td><%= student.password %></td>
      <td><%= student.role %></td>
      <td><%= student.first_name %></td>
      <td><%= student.last_name %></td>
      <td><%= student.address %></td>
      <td><%= student.college %></td>
      <td><%= student.email %></td>
      <td><%= link_to 'Show', student %></td>
      <td><% if current_user.role == "a"%> <%= link_to 'Edit', edit_student_path(student) %><%end%> </td>
      <td><% if current_user.role == "a"%><%= link_to 'Destroy',student, :method =>:delete, :confirm => 'Are you sure?' %><%end%></td>
    </tr>
  <% end %>
</table>
</center>

app/views/students/login.html.erb
<%= stylesheet_link_tag 'application' %>
<%= form_for @student, :url => { :action => "check_login" } do |f|%>
<% if @student.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@s.errors.count, "error") %> prohibited this student from being saved:</h2>
      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
    <div class="form_content">
        <h2 >Login Here</h2>
        <div class="field1"> 
          <%= f.label :user %>
        </div>
        <div id="user">
          <%= f.text_field :user %>
        </div>
        <div class="field2"> 
          <%= f.label :password %>
        </div>
        <div id="password">
          <%= f.password_field :password %>
        </div>
        <div class="field3">
          <%= label_tag(:remember_me, "Remember") %>
        </div>
        <div id="remember_me">
          <%= check_box_tag(:remember_me) %>
        </div>
        <div id="actions">
          <%= f.submit 'Login' %>
        </div>
    </div>
    <center><b><%= notice %></b></center>
<% end %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>
<table border=1 align="center">
  <tr>
    <td><b>User:</b></td>
    <td> <%= @student.user %></td>
  </tr>

  <tr>
    <td><b>Password:</b></td>
    <td>  <%= @student.password %></td>
  </tr>

  <tr>
    <td><b>Role:</b></td>
    <td><%= @student.role %></td>
  </tr>

  <tr>
    <td><b>First name:</b></td>
    <td>    <%= @student.first_name %></td>
  </tr>

  <tr>
    <td><b>Last name:</b></td>
    <td>  <%= @student.last_name %></td>
  </tr>

  <tr>
    <td><b>Address:</b></td>
    <td>  <%= @student.address %></td>
  </tr>

  <tr>
    <td><b>College:</b></td>
    <td>  <%= @student.college %></td>
  </tr>

  <tr>
    <td><b>Email:</b></td>
    <td>  <%= @student.email %></td>
  </tr>

  <tr>
    <td colspan=2><b><%= link_to 'Edit', edit_student_path(@student) %></b></td>
  </tr>

</table>